#################
### AUTOSTART  ###
#################

# Wallpaper daemon + restore last-used wallpaper
exec-once = swww-daemon
exec-once = swww restore

exec-once = waybar
exec-once = mako
exec-once = hyprlock

#exec-once = ~/.config/waybar/scripts/launch.sh
