################
### MONITORS ###
################

# See https://wiki.hypr.land/Configuring/Monitors/
# External monitor (main) on the left
monitor = HDMI-A-1, 2560x1440@60, 0x0, 1

# Laptop screen on the right of the external
monitor = eDP-1, 1920x1080@165, 2560x0, 1
