# vim:ft=kitty
# Theme: Dracula
# https://draculatheme.com/

# The basic colors
foreground              #f8f8f2
background              #282a36
selection_foreground    #f8f8f2
selection_background    #44475a

# Cursor colors
cursor                  #f8f8f2
cursor_text_color       #282a36

# URL underline color when hovering with mouse
url_color               #8be9fd

# Kitty window border colors
active_border_color     #bd93f9
inactive_border_color   #44475a
bell_border_color       #ff5555

# Tab bar colors
active_tab_foreground   #282a36
active_tab_background   #bd93f9
inactive_tab_foreground #f8f8f2
inactive_tab_background #44475a
tab_bar_background      #282a36

# The 16 terminal colors
color0  #21222c
color1  #ff5555
color2  #50fa7b
color3  #f1fa8c
color4  #bd93f9
color5  #ff79c6
color6  #8be9fd
color7  #f8f8f2
color8  #6272a4
color9  #ff6e6e
color10 #69ff94
color11 #ffffa5
color12 #d6acff
color13 #ff92df
color14 #a4ffff
color15 #ffffff
