# vim:ft=kitty
# Theme: Gruvbox Light
# https://github.com/morhetz/gruvbox

# The basic colors
foreground              #3c3836
background              #fbf1c7
selection_foreground    #3c3836
selection_background    #bdae93

# Cursor colors
cursor                  #3c3836
cursor_text_color       #fbf1c7

# URL underline color when hovering with mouse
url_color               #076678

# Kitty window border colors
active_border_color     #076678
inactive_border_color   #bdae93
bell_border_color       #9d0006

# Tab bar colors
active_tab_foreground   #fbf1c7
active_tab_background   #076678
inactive_tab_foreground #7c6f64
inactive_tab_background #ebdbb2
tab_bar_background      #fbf1c7

# The 16 terminal colors
color0  #fbf1c7
color1  #cc241d
color2  #98971a
color3  #d79921
color4  #458588
color5  #b16286
color6  #689d6a
color7  #3c3836
color8  #928374
color9  #9d0006
color10 #79740e
color11 #b57614
color12 #076678
color13 #8f3f71
color14 #427b58
color15 #3c3836
