general {
    hide_cursor = true
    no_fade_in = false
    no_fade_out = false
}

background {
    monitor =
    path = screenshot
    blur_passes = 3
    blur_size = 8
    noise = 0.0117
    contrast = 0.8916
    brightness = 0.8172
    vibrancy = 0.1696
    vibrancy_darkness = 0.0
}

input-field {
    monitor =
    size = 300, 50
    outline_thickness = 3
    dots_size = 0.33
    dots_spacing = 0.15
    fade_on_empty = true
    fade_timeout = 1000
    placeholder_text = <i>Password...</i>
    fail_text = <i>Failure</i>
    position = 0, -20
    halign = center
    valign = center

    colors {
        background = rgba(16, 20, 24, 1.0)
        placeholder = rgba(255, 255, 255, 1.0)
        text = rgba(255, 255, 255, 1.0)
        fail = rgba(255, 98, 77, 1.0)
        outline = rgba(196, 223, 255, 1.0)
    }
}

label {
    monitor =
    text = $TIME
    color = rgba(255, 255, 255, 1.0)
    font_size = 90
    font_family = JetBrains Mono
    position = 0, 200
    halign = center
    valign = center
    transform = rotate(0)
}